name: Update Last Modified Date

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.email "zhenling_mo@qq.com"
          git config --global user.name "mozhenling"
      - name: Update Last Modified Date
        run: |
          for file in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}); do
            if [[ $file == *.md ]]; then
              # Check if the file has a last_modified_at field
              if grep -q '^last_modified_at:' "$file"; then
                sed -i 's/^last_modified_at:.*/last_modified_at: '"$(date '+%d %B %Y')"'/' "$file"
              else
                sed -i '2i last_modified_at: '"$(date '+%d %B %Y')"'\'$'\n' "$file"
              fi
              git add "$file"
            fi
          done
          git commit -m "Update last modified dates" || echo "No changes to commit"
          git push || echo "No changes to push"